name: Go

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Check formatting
      run: diff -u <(echo -n) <(gofmt -d .)
    - name: Test
      run: go test -v ./...